spring:
  datasource:
    driverClassName: org.mariadb.jdbc.Driver
    password:
    username: utopia
    url: jdbc:mariadb://localhost:3306/utopia?useUnicode=true&characterEncoding=utf8&serverTimeZone=Asia/Seoul&allowPublicKeyRetrieval=true&useSSL=false
  thymeleaf:
    cache: 'false'
    prefix: file:src/main/resources/templates/
  devtools:
    restart:
      enabled: 'true'
    livereload:
      enabled: 'true'
  jpa:
    properties:
      hibernate:
        use_sql_comments: 'true'
        format_sql: 'true'
        show_sql: 'true'
    hibernate:
      ddl-auto: update
postImgLocation: C:/post/img/
logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: trace